allowBuilds:
  esbuild: false
  workerd: false
catalogMode: strict
cleanupUnusedCatalogs: true
catalog:
  "@atcute/atproto": 4.0.4
  "@atcute/bluesky": 4.0.17
  "@atcute/client": 5.1.1
  "@atcute/identity": 2.0.2
  "@atcute/identity-resolver": 2.0.1
  "@atcute/identity-resolver-node": 2.0.1
  "@atcute/lexicons": 2.0.3
  "@atcute/oauth-node-client": 2.0.1
  "@cloudflare/vite-plugin": 1.50.0
  "@hiogawa/vite-plugin-fullstack": 0.0.11
  "@tailwindcss/vite": 4.3.3
  "@types/node": ^24.13.3
  basecoat-css: 1.0.2
  chart.js: ^4.5.1
  hono: 4.12.34
  htmx.org: 4.0.0-beta6
  invokers-polyfill: 1.0.3
  srv-jsx: 0.0.12
  tailwindcss: 4.3.3
  template-for-polyfill: 0.1.1
  typescript: 7.0.2
  valibot: 1.4.2
  vite: npm:@voidzero-dev/vite-plus-core@0.2.7
  vite-plus: 0.2.7
  wrangler: 4.118.0
overrides:
  vite: npm:@voidzero-dev/vite-plus-core@0.2.7
minimumReleaseAgeExclude:
  - srv-jsx
