allowBuilds:
  esbuild: false
  workerd: false
catalogMode: strict
cleanupUnusedCatalogs: true
catalog:
  "@atcute/atproto": 4.0.4
  "@atcute/cid": 2.4.2
  "@atcute/client": 5.1.1
  "@atcute/identity-resolver": 2.0.1
  "@atcute/identity-resolver-node": 2.0.1
  "@atcute/jetstream": 2.0.2
  "@atcute/lex-cli": 3.2.1
  "@atcute/lexicons": 2.0.3
  "@atcute/oauth-node-client": 2.0.1
  "@atcute/tid": 1.1.4
  "@cloudflare/vite-plugin": 1.51.0
  "@hiogawa/vite-plugin-fullstack": 0.0.11
  "@npm/types": 2.1.0
  "@peculiar/x509": 2.0.0
  "@standard-schema/spec": 1.1.0
  "@tailwindcss/vite": 4.3.3
  "@types/node": ^24.13.3
  "@types/validate-npm-package-name": 4.0.2
  basecoat-css: 1.0.2
  chart.js: 4.5.1
  drizzle-kit: 1.0.0-rc.4
  drizzle-orm: 1.0.0-rc.4
  hono: 4.13.0
  htmx.org: 4.0.0-beta6
  invokers-polyfill: 1.0.3
  jose: 6.2.8
  marked: 18.0.9
  package-json-validator: 1.6.0
  reflect-metadata: 0.2.2
  srv-jsx: 0.0.12
  tailwindcss: 4.3.3
  template-for-polyfill: 0.1.1
  typescript: 7.0.2
  uuid: 14.0.1
  valibot: 1.4.2
  validate-npm-package-name: 8.0.0
  vite: npm:@voidzero-dev/vite-plus-core@0.2.7
  vite-plus: 0.2.7
  wrangler: 4.119.0
overrides:
  vite: npm:@voidzero-dev/vite-plus-core@0.2.7
peerDependencyRules:
  allowAny:
    - vite
minimumReleaseAgeExclude:
  - srv-jsx@0.0.12
  - hono-atcute@0.0.10
  - "@cloudflare/vite-plugin@1.51.0"
  - miniflare@5.20260801.0-alpha
  - wrangler@4.119.0
